"""Generate all public app pages from the shared portfolio and one template."""
import html
import json
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SITE = 'https://jn86vi.github.io'


def app_data():
    source = (ROOT / 'assets/portfolio-v2.js').read_text()
    return json.JSONDecoder().raw_decode(source.split('const portfolioApps = ', 1)[1])[0]


def page(app):
    esc = html.escape
    name = esc(app['name'])
    copy = app['copy']['en']
    description = esc(copy['summary'], quote=True)
    url = f"{SITE}/apps/{app['id']}.html"
    image = app['icon'] or 'assets/JN86_Logo_Lockup_White_Transparent.png'
    icon = f'<img class="detail-icon" src="../{app["icon"]}" alt="">' if app['icon'] else ''
    options = ''.join(f'<option value="{value}">{label}</option>' for value, label in [
        ('en', 'English'), ('hu', 'Magyar'), ('de', 'Deutsch'), ('es', 'Español'),
        ('fr', 'Français'), ('pt-BR', 'Português (Brasil)'), ('pl', 'Polski'), ('it', 'Italiano')])
    nav = ''.join(f'<a href="../{path}.html" data-i18n="nav_{path}">{label}</a>' for path, label in [
        ('apps', 'Apps'), ('support', 'Support'), ('privacy', 'Privacy'), ('contact', 'Contact')])
    status = 'Coming soon' if app['status'] == 'soon' else 'In the works'
    features = ''.join(f'<li>{esc(text)}</li>' for text in copy['features'])
    availability = 'Coming soon. This app is not yet available to download.' if app['status'] == 'soon' else 'This app is being created. The features described here are planned; it is not yet available to download.'
    related = ''
    if app['id'] in ['unit-converter', 'ott-e']:
        related = f'''<a class="btn secondary" href="../help/{app['id']}.html" data-i18n="app_help">App help</a>
          <a class="btn secondary" href="../privacy/{app['id']}.html" data-i18n="nav_privacy">Privacy</a>'''
    return f'''<!doctype html>
<!-- Generated by scripts/build-details.py from assets/portfolio-v2.js. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#0B0F14">
  <meta name="robots" content="index,follow">
  <meta name="description" content="{description}">
  <link rel="canonical" href="{url}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{name} — App details — JN86">
  <meta property="og:description" content="{description}">
  <meta property="og:url" content="{url}">
  <meta property="og:image" content="{SITE}/{image}">
  <meta name="twitter:card" content="summary_large_image">
  <title>{name} — App details — JN86</title>
  <link rel="icon" type="image/png" href="../assets/JN86_Logo_Lockup_White_Transparent.png">
  <link rel="stylesheet" href="../assets/style.css?v=9">
  <link rel="stylesheet" href="../assets/pages.css?v=3">
</head>
<body data-app="{app['id']}">
<header class="site-header"><div class="wrap nav-wrap">
  <a class="brand" href="../index.html" aria-label="JN86 home" data-i18n-aria="home_label"><img src="../assets/JN86_Logo_Lockup_White_Transparent.png" alt="JN86" class="brand-logo"></a>
  <nav class="nav" aria-label="Main navigation" data-i18n-aria="nav_label">{nav}</nav>
  <label class="language"><span class="sr-only" data-i18n="language">Language</span><select id="languageSelect" aria-label="Language" data-i18n-aria="language">{options}</select></label>
  <button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="mobileNav"><span></span><span></span><span></span></button>
</div><nav id="mobileNav" class="mobile-nav" aria-label="Mobile navigation" data-i18n-aria="mobile_nav_label">{nav}</nav></header>
<main>
  <section class="detail-hero"><div class="wrap detail-grid{' without-icon' if not icon else ''}">{icon}<div>
    <p class="eyebrow" data-i18n="detail_title">App details</p>
    <h1>{name}</h1>
    <p class="lead" data-app-summary>{esc(copy['summary'])}</p>
    <div class="detail-meta"><span class="badge {app['status']}" data-app-status>{status}</span><span class="badge neutral">Android</span></div>
  </div></div></section>
  <section class="section"><div class="wrap split">
    <div><h2 data-i18n="purpose_title">What it’s for</h2><p data-app-overview>{esc(copy['overview'])}</p></div>
    <div class="panel"><h3 data-i18n="features_title">Main features</h3><ul class="feature-list" data-app-features>{features}</ul></div>
  </div></section>
  <section class="section alt"><div class="wrap">
    <h2 data-i18n="availability_title">Availability</h2>
    <p class="lead" data-app-availability>{availability}</p>
    <div class="hero-actions"><a class="btn secondary" href="../apps.html" data-i18n="back_apps">← Back to apps</a>{related}</div>
  </div></section>
</main>
<footer><div class="wrap footer"><div><img src="../assets/JN86_Logo_Lockup_White_Transparent.png" alt="JN86" class="footer-logo"><p>Fast. Simple. Reliable.</p></div><p>© <span id="year"></span> JN86 · <span data-i18n="developer">Developer: JN86VI</span></p></div></footer>
<script src="../assets/site.js?v=6"></script>
<script src="../assets/portfolio-v2.js?v=3"></script>
<script src="../assets/mobile-menu.js?v=6"></script>
<script src="../assets/app-detail.js?v=1"></script>
</body>
</html>
'''


def outputs():
    apps = app_data()
    pages = {ROOT / f"apps/{app['id']}.html": page(app) for app in apps}
    namespace = 'http://www.sitemaps.org/schemas/sitemap/0.9'
    ET.register_namespace('', namespace)
    sitemap = ET.fromstring((ROOT / 'sitemap.xml').read_text())
    existing = {el.text for el in sitemap.findall(f'{{{namespace}}}url/{{{namespace}}}loc')}
    for app in apps:
        url = f"{SITE}/apps/{app['id']}.html"
        if url not in existing:
            entry = ET.SubElement(sitemap, f'{{{namespace}}}url')
            ET.SubElement(entry, f'{{{namespace}}}loc').text = url
    ET.indent(sitemap, space='  ')
    pages[ROOT / 'sitemap.xml'] = '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(sitemap, encoding='unicode') + '\n'
    return pages


if __name__ == '__main__':
    import sys
    generated = outputs()
    if '--check' in sys.argv:
        stale = [str(path.relative_to(ROOT)) for path, text in generated.items() if not path.exists() or path.read_text() != text]
        if stale:
            raise SystemExit('Stale generated pages: ' + ', '.join(stale))
        print('PASS: all 25 detail pages and the sitemap match the shared template/data')
    else:
        for path, text in generated.items():
            path.write_text(text)
        print('Generated 25 app pages and updated the sitemap')
